cloud:
  aws:
    region:
      static: us-east-1
    stack:
        auto: false
    credentials:
        access-key: AKIA6H6AJRDP76LRCWF2
        secret-key: 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
logging:
  level:
    com:
      amazonans:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
                
            
       